# Generated by Django 4.1 on 2023-04-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
