# Generated by Django 4.1 on 2023-04-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0003_alter_add_category_options_add_category_display_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_category',
            options={},
        ),
    ]
