# Generated by Django 4.1 on 2023-04-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0004_alter_add_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_category',
            name='display_id',
        ),
    ]
