# Generated by Django 4.1 on 2023-04-18 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0005_remove_add_category_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
