# Generated by Django 4.1 on 2023-04-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CategoryApp', '0008_alter_add_category_category_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_company_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_contact_number', models.CharField(max_length=16)),
                ('vehicle_in_time', models.DateTimeField()),
                ('vehicle_out_time', models.DateTimeField()),
                ('vehicle_status', models.CharField(choices=[('vechicle in', 'vehicle in'), ('vechicle out', 'vehicle out')], default='vechicle in', max_length=100)),
                ('parking_number', models.CharField(max_length=100, unique=True)),
                ('vehicel_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CategoryApp.add_category')),
            ],
        ),
    ]
