# Generated by Django 4.1 on 2023-04-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VManageIn_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclein',
            name='vehicle_out_time',
        ),
        migrations.AddField(
            model_name='vehiclein',
            name='vehicle_time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclein',
            name='parking_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclein',
            name='vehicle_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
