# Generated by Django 4.1 on 2023-05-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VManageIn_App', '0003_vehiclein_parking_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclein',
            name='parking_charges',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
