# Generated by Django 4.1 on 2023-05-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VManageIn_App', '0004_alter_vehiclein_parking_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclein',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
